// This file was auto-generated by Fern from our API Definition.

package client

import (
	http "net/http"
	account "github.com/mailmus/mailmus-go/account"
	accountanalytics "github.com/mailmus/mailmus-go/accountanalytics"
	analytics "github.com/mailmus/mailmus-go/analytics"
	apikeys "github.com/mailmus/mailmus-go/apikeys"
	app "github.com/mailmus/mailmus-go/app"
	apps "github.com/mailmus/mailmus-go/apps"
	audiences "github.com/mailmus/mailmus-go/audiences"
	auth "github.com/mailmus/mailmus-go/auth"
	automations "github.com/mailmus/mailmus-go/automations"
	billing "github.com/mailmus/mailmus-go/billing"
	billingwebhook "github.com/mailmus/mailmus-go/billingwebhook"
	campaigns "github.com/mailmus/mailmus-go/campaigns"
	contacts "github.com/mailmus/mailmus-go/contacts"
	core "github.com/mailmus/mailmus-go/core"
	domains "github.com/mailmus/mailmus-go/domains"
	emails "github.com/mailmus/mailmus-go/emails"
	internal "github.com/mailmus/mailmus-go/internal"
	option "github.com/mailmus/mailmus-go/option"
	public "github.com/mailmus/mailmus-go/public"
	seswebhook "github.com/mailmus/mailmus-go/seswebhook"
	suppressions "github.com/mailmus/mailmus-go/suppressions"
	templates "github.com/mailmus/mailmus-go/templates"
	tracking "github.com/mailmus/mailmus-go/tracking"
	usage "github.com/mailmus/mailmus-go/usage"
	webhooks "github.com/mailmus/mailmus-go/webhooks"
)

type Client struct {
	baseURL string
	caller  *internal.Caller
	header  http.Header

	App              *app.Client
	Suppressions     *suppressions.Client
	Auth             *auth.Client
	SesWebhook       *seswebhook.Client
	Webhooks         *webhooks.Client
	Domains          *domains.Client
	Templates        *templates.Client
	APIKeys          *apikeys.Client
	Contacts         *contacts.Client
	Automations      *automations.Client
	Tracking         *tracking.Client
	Campaigns        *campaigns.Client
	Usage            *usage.Client
	Billing          *billing.Client
	BillingWebhook   *billingwebhook.Client
	Emails           *emails.Client
	Audiences        *audiences.Client
	Account          *account.Client
	Apps             *apps.Client
	Public           *public.Client
	Analytics        *analytics.Client
	AccountAnalytics *accountanalytics.Client
}

func NewClient(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	return &Client{
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
		header:           options.ToHeader(),
		App:              app.NewClient(opts...),
		Suppressions:     suppressions.NewClient(opts...),
		Auth:             auth.NewClient(opts...),
		SesWebhook:       seswebhook.NewClient(opts...),
		Webhooks:         webhooks.NewClient(opts...),
		Domains:          domains.NewClient(opts...),
		Templates:        templates.NewClient(opts...),
		APIKeys:          apikeys.NewClient(opts...),
		Contacts:         contacts.NewClient(opts...),
		Automations:      automations.NewClient(opts...),
		Tracking:         tracking.NewClient(opts...),
		Campaigns:        campaigns.NewClient(opts...),
		Usage:            usage.NewClient(opts...),
		Billing:          billing.NewClient(opts...),
		BillingWebhook:   billingwebhook.NewClient(opts...),
		Emails:           emails.NewClient(opts...),
		Audiences:        audiences.NewClient(opts...),
		Account:          account.NewClient(opts...),
		Apps:             apps.NewClient(opts...),
		Public:           public.NewClient(opts...),
		Analytics:        analytics.NewClient(opts...),
		AccountAnalytics: accountanalytics.NewClient(opts...),
	}
}
