// This file was auto-generated by Fern from our API Definition.

package mailmus

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/mailmus/mailmus-go/internal"
)

type AppMailAnalyticsGetRequest struct {
	Days float64 `json:"-" url:"days"`
}

type AutomationsAnalyticsDto struct {
	TotalRuns float64 `json:"totalRuns" url:"totalRuns"`
	Completed float64 `json:"completed" url:"completed"`
	Failed    float64 `json:"failed" url:"failed"`
	// Exécutions abouties rapportées au total.
	SuccessRate float64 `json:"successRate" url:"successRate"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (a *AutomationsAnalyticsDto) GetTotalRuns() float64 {
	if a == nil {
		return 0
	}
	return a.TotalRuns
}

func (a *AutomationsAnalyticsDto) GetCompleted() float64 {
	if a == nil {
		return 0
	}
	return a.Completed
}

func (a *AutomationsAnalyticsDto) GetFailed() float64 {
	if a == nil {
		return 0
	}
	return a.Failed
}

func (a *AutomationsAnalyticsDto) GetSuccessRate() float64 {
	if a == nil {
		return 0
	}
	return a.SuccessRate
}

func (a *AutomationsAnalyticsDto) GetExtraProperties() map[string]interface{} {
	return a.extraProperties
}

func (a *AutomationsAnalyticsDto) UnmarshalJSON(data []byte) error {
	type unmarshaler AutomationsAnalyticsDto
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*a = AutomationsAnalyticsDto(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *a)
	if err != nil {
		return err
	}
	a.extraProperties = extraProperties
	a.rawJSON = json.RawMessage(data)
	return nil
}

func (a *AutomationsAnalyticsDto) String() string {
	if len(a.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(a.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(a); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", a)
}

type CampaignsAnalyticsDto struct {
	Total float64 `json:"total" url:"total"`
	// Campagnes réellement parties.
	Sent float64 `json:"sent" url:"sent"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CampaignsAnalyticsDto) GetTotal() float64 {
	if c == nil {
		return 0
	}
	return c.Total
}

func (c *CampaignsAnalyticsDto) GetSent() float64 {
	if c == nil {
		return 0
	}
	return c.Sent
}

func (c *CampaignsAnalyticsDto) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CampaignsAnalyticsDto) UnmarshalJSON(data []byte) error {
	type unmarshaler CampaignsAnalyticsDto
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CampaignsAnalyticsDto(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CampaignsAnalyticsDto) String() string {
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

type ContactsAnalyticsDto struct {
	Total        float64 `json:"total" url:"total"`
	Unsubscribed float64 `json:"unsubscribed" url:"unsubscribed"`
	// Désinscrits rapportés au total des contacts.
	UnsubscribeRate float64 `json:"unsubscribeRate" url:"unsubscribeRate"`
	NewLast30Days   float64 `json:"newLast30Days" url:"newLast30Days"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *ContactsAnalyticsDto) GetTotal() float64 {
	if c == nil {
		return 0
	}
	return c.Total
}

func (c *ContactsAnalyticsDto) GetUnsubscribed() float64 {
	if c == nil {
		return 0
	}
	return c.Unsubscribed
}

func (c *ContactsAnalyticsDto) GetUnsubscribeRate() float64 {
	if c == nil {
		return 0
	}
	return c.UnsubscribeRate
}

func (c *ContactsAnalyticsDto) GetNewLast30Days() float64 {
	if c == nil {
		return 0
	}
	return c.NewLast30Days
}

func (c *ContactsAnalyticsDto) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *ContactsAnalyticsDto) UnmarshalJSON(data []byte) error {
	type unmarshaler ContactsAnalyticsDto
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = ContactsAnalyticsDto(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *ContactsAnalyticsDto) String() string {
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

type MailAnalyticsResponseDto struct {
	ProjectID   string                   `json:"projectId" url:"projectId"`
	ProjectName string                   `json:"projectName" url:"projectName"`
	Contacts    *ContactsAnalyticsDto    `json:"contacts,omitempty" url:"contacts,omitempty"`
	Sends       *SendsAnalyticsDto       `json:"sends,omitempty" url:"sends,omitempty"`
	Campaigns   *CampaignsAnalyticsDto   `json:"campaigns,omitempty" url:"campaigns,omitempty"`
	Automations *AutomationsAnalyticsDto `json:"automations,omitempty" url:"automations,omitempty"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (m *MailAnalyticsResponseDto) GetProjectID() string {
	if m == nil {
		return ""
	}
	return m.ProjectID
}

func (m *MailAnalyticsResponseDto) GetProjectName() string {
	if m == nil {
		return ""
	}
	return m.ProjectName
}

func (m *MailAnalyticsResponseDto) GetContacts() *ContactsAnalyticsDto {
	if m == nil {
		return nil
	}
	return m.Contacts
}

func (m *MailAnalyticsResponseDto) GetSends() *SendsAnalyticsDto {
	if m == nil {
		return nil
	}
	return m.Sends
}

func (m *MailAnalyticsResponseDto) GetCampaigns() *CampaignsAnalyticsDto {
	if m == nil {
		return nil
	}
	return m.Campaigns
}

func (m *MailAnalyticsResponseDto) GetAutomations() *AutomationsAnalyticsDto {
	if m == nil {
		return nil
	}
	return m.Automations
}

func (m *MailAnalyticsResponseDto) GetExtraProperties() map[string]interface{} {
	return m.extraProperties
}

func (m *MailAnalyticsResponseDto) UnmarshalJSON(data []byte) error {
	type unmarshaler MailAnalyticsResponseDto
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*m = MailAnalyticsResponseDto(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *m)
	if err != nil {
		return err
	}
	m.extraProperties = extraProperties
	m.rawJSON = json.RawMessage(data)
	return nil
}

func (m *MailAnalyticsResponseDto) String() string {
	if len(m.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(m.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(m); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", m)
}

type MailDomainStatsDto struct {
	Domain   string                   `json:"domain" url:"domain"`
	DomainID string                   `json:"domainId" url:"domainId"`
	Status   MailDomainStatsDtoStatus `json:"status" url:"status"`
	// Messages émis depuis ce domaine.
	Total      float64 `json:"total" url:"total"`
	Bounced    float64 `json:"bounced" url:"bounced"`
	Complained float64 `json:"complained" url:"complained"`
	Opened     float64 `json:"opened" url:"opened"`
	Clicked    float64 `json:"clicked" url:"clicked"`
	// Rejets rapportés aux messages émis.
	BounceRate float64 `json:"bounceRate" url:"bounceRate"`
	// Plaintes rapportées aux messages émis.
	ComplaintRate float64 `json:"complaintRate" url:"complaintRate"`
	// Ouvertures rapportées aux messages remis.
	OpenRate float64 `json:"openRate" url:"openRate"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (m *MailDomainStatsDto) GetDomain() string {
	if m == nil {
		return ""
	}
	return m.Domain
}

func (m *MailDomainStatsDto) GetDomainID() string {
	if m == nil {
		return ""
	}
	return m.DomainID
}

func (m *MailDomainStatsDto) GetStatus() MailDomainStatsDtoStatus {
	if m == nil {
		return ""
	}
	return m.Status
}

func (m *MailDomainStatsDto) GetTotal() float64 {
	if m == nil {
		return 0
	}
	return m.Total
}

func (m *MailDomainStatsDto) GetBounced() float64 {
	if m == nil {
		return 0
	}
	return m.Bounced
}

func (m *MailDomainStatsDto) GetComplained() float64 {
	if m == nil {
		return 0
	}
	return m.Complained
}

func (m *MailDomainStatsDto) GetOpened() float64 {
	if m == nil {
		return 0
	}
	return m.Opened
}

func (m *MailDomainStatsDto) GetClicked() float64 {
	if m == nil {
		return 0
	}
	return m.Clicked
}

func (m *MailDomainStatsDto) GetBounceRate() float64 {
	if m == nil {
		return 0
	}
	return m.BounceRate
}

func (m *MailDomainStatsDto) GetComplaintRate() float64 {
	if m == nil {
		return 0
	}
	return m.ComplaintRate
}

func (m *MailDomainStatsDto) GetOpenRate() float64 {
	if m == nil {
		return 0
	}
	return m.OpenRate
}

func (m *MailDomainStatsDto) GetExtraProperties() map[string]interface{} {
	return m.extraProperties
}

func (m *MailDomainStatsDto) UnmarshalJSON(data []byte) error {
	type unmarshaler MailDomainStatsDto
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*m = MailDomainStatsDto(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *m)
	if err != nil {
		return err
	}
	m.extraProperties = extraProperties
	m.rawJSON = json.RawMessage(data)
	return nil
}

func (m *MailDomainStatsDto) String() string {
	if len(m.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(m.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(m); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", m)
}

type MailDomainStatsDtoStatus string

const (
	MailDomainStatsDtoStatusPending  MailDomainStatsDtoStatus = "PENDING"
	MailDomainStatsDtoStatusVerified MailDomainStatsDtoStatus = "VERIFIED"
	MailDomainStatsDtoStatusFailed   MailDomainStatsDtoStatus = "FAILED"
)

func NewMailDomainStatsDtoStatusFromString(s string) (MailDomainStatsDtoStatus, error) {
	switch s {
	case "PENDING":
		return MailDomainStatsDtoStatusPending, nil
	case "VERIFIED":
		return MailDomainStatsDtoStatusVerified, nil
	case "FAILED":
		return MailDomainStatsDtoStatusFailed, nil
	}
	var t MailDomainStatsDtoStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (m MailDomainStatsDtoStatus) Ptr() *MailDomainStatsDtoStatus {
	return &m
}

type MailTimeSeriesPointDto struct {
	// Jour, en UTC.
	Date    string  `json:"date" url:"date"`
	Sent    float64 `json:"sent" url:"sent"`
	Opened  float64 `json:"opened" url:"opened"`
	Clicked float64 `json:"clicked" url:"clicked"`
	Bounced float64 `json:"bounced" url:"bounced"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (m *MailTimeSeriesPointDto) GetDate() string {
	if m == nil {
		return ""
	}
	return m.Date
}

func (m *MailTimeSeriesPointDto) GetSent() float64 {
	if m == nil {
		return 0
	}
	return m.Sent
}

func (m *MailTimeSeriesPointDto) GetOpened() float64 {
	if m == nil {
		return 0
	}
	return m.Opened
}

func (m *MailTimeSeriesPointDto) GetClicked() float64 {
	if m == nil {
		return 0
	}
	return m.Clicked
}

func (m *MailTimeSeriesPointDto) GetBounced() float64 {
	if m == nil {
		return 0
	}
	return m.Bounced
}

func (m *MailTimeSeriesPointDto) GetExtraProperties() map[string]interface{} {
	return m.extraProperties
}

func (m *MailTimeSeriesPointDto) UnmarshalJSON(data []byte) error {
	type unmarshaler MailTimeSeriesPointDto
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*m = MailTimeSeriesPointDto(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *m)
	if err != nil {
		return err
	}
	m.extraProperties = extraProperties
	m.rawJSON = json.RawMessage(data)
	return nil
}

func (m *MailTimeSeriesPointDto) String() string {
	if len(m.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(m.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(m); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", m)
}

type SendsAnalyticsDto struct {
	Total      float64 `json:"total" url:"total"`
	Delivered  float64 `json:"delivered" url:"delivered"`
	Opened     float64 `json:"opened" url:"opened"`
	Clicked    float64 `json:"clicked" url:"clicked"`
	Bounced    float64 `json:"bounced" url:"bounced"`
	Complained float64 `json:"complained" url:"complained"`
	Failed     float64 `json:"failed" url:"failed"`
	Last30Days float64 `json:"last30Days" url:"last30Days"`
	// Ouvertures rapportées aux messages remis.
	OpenRate float64 `json:"openRate" url:"openRate"`
	// Clics rapportés aux messages remis.
	ClickRate float64 `json:"clickRate" url:"clickRate"`
	// Rejets rapportés aux messages émis.
	BounceRate float64 `json:"bounceRate" url:"bounceRate"`
	// Plaintes rapportées aux messages émis.
	ComplaintRate float64 `json:"complaintRate" url:"complaintRate"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *SendsAnalyticsDto) GetTotal() float64 {
	if s == nil {
		return 0
	}
	return s.Total
}

func (s *SendsAnalyticsDto) GetDelivered() float64 {
	if s == nil {
		return 0
	}
	return s.Delivered
}

func (s *SendsAnalyticsDto) GetOpened() float64 {
	if s == nil {
		return 0
	}
	return s.Opened
}

func (s *SendsAnalyticsDto) GetClicked() float64 {
	if s == nil {
		return 0
	}
	return s.Clicked
}

func (s *SendsAnalyticsDto) GetBounced() float64 {
	if s == nil {
		return 0
	}
	return s.Bounced
}

func (s *SendsAnalyticsDto) GetComplained() float64 {
	if s == nil {
		return 0
	}
	return s.Complained
}

func (s *SendsAnalyticsDto) GetFailed() float64 {
	if s == nil {
		return 0
	}
	return s.Failed
}

func (s *SendsAnalyticsDto) GetLast30Days() float64 {
	if s == nil {
		return 0
	}
	return s.Last30Days
}

func (s *SendsAnalyticsDto) GetOpenRate() float64 {
	if s == nil {
		return 0
	}
	return s.OpenRate
}

func (s *SendsAnalyticsDto) GetClickRate() float64 {
	if s == nil {
		return 0
	}
	return s.ClickRate
}

func (s *SendsAnalyticsDto) GetBounceRate() float64 {
	if s == nil {
		return 0
	}
	return s.BounceRate
}

func (s *SendsAnalyticsDto) GetComplaintRate() float64 {
	if s == nil {
		return 0
	}
	return s.ComplaintRate
}

func (s *SendsAnalyticsDto) GetExtraProperties() map[string]interface{} {
	return s.extraProperties
}

func (s *SendsAnalyticsDto) UnmarshalJSON(data []byte) error {
	type unmarshaler SendsAnalyticsDto
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = SendsAnalyticsDto(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *SendsAnalyticsDto) String() string {
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}
