// This file was auto-generated by Fern from our API Definition.

package mailmus

type CreateAppDto struct {
	Name string `json:"name" url:"-"`
}

type UpdateAppDto struct {
	Name string `json:"name" url:"-"`
}
