// This file was auto-generated by Fern from our API Definition.

package mailmus

import (
	fmt "fmt"
)

type CreateCheckoutDto struct {
	Plan CreateCheckoutDtoPlan `json:"plan" url:"-"`
}

type CreateCheckoutDtoPlan string

const (
	CreateCheckoutDtoPlanPro   CreateCheckoutDtoPlan = "PRO"
	CreateCheckoutDtoPlanScale CreateCheckoutDtoPlan = "SCALE"
)

func NewCreateCheckoutDtoPlanFromString(s string) (CreateCheckoutDtoPlan, error) {
	switch s {
	case "PRO":
		return CreateCheckoutDtoPlanPro, nil
	case "SCALE":
		return CreateCheckoutDtoPlanScale, nil
	}
	var t CreateCheckoutDtoPlan
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CreateCheckoutDtoPlan) Ptr() *CreateCheckoutDtoPlan {
	return &c
}
