// This file was auto-generated by Fern from our API Definition.

package mailmus

type BatchImportContactsDto struct {
}

type CreateContactDto struct {
	Email      string                 `json:"email" url:"-"`
	Attributes map[string]interface{} `json:"attributes,omitempty" url:"-"`
}

type ContactsControllerListRequest struct {
	Status    string `json:"-" url:"status"`
	Q         string `json:"-" url:"q"`
	AttrKey   string `json:"-" url:"attrKey"`
	AttrValue string `json:"-" url:"attrValue"`
}

type UpdateContactDto struct {
	Attributes map[string]interface{} `json:"attributes,omitempty" url:"-"`
}
