// This file was auto-generated by Fern from our API Definition.

package mailmus

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/mailmus/mailmus-go/internal"
	time "time"
)

type CustomerAdminListRequest struct {
	Q        string `json:"-" url:"q"`
	Status   string `json:"-" url:"status"`
	Provider string `json:"-" url:"provider"`
}

type UpdateMetadataDto struct {
	Metadata map[string]interface{} `json:"metadata,omitempty" url:"-"`
}

type UpdateRolesDto struct {
	Roles []string `json:"roles,omitempty" url:"-"`
}

type AuditLogEntryResponseDto struct {
	ID string `json:"id" url:"id"`
	// Qui a agi.
	ActorEmail string `json:"actorEmail" url:"actorEmail"`
	Action     string `json:"action" url:"action"`
	// Nature de l’objet visé.
	TargetType string                 `json:"targetType" url:"targetType"`
	TargetID   map[string]interface{} `json:"targetId,omitempty" url:"targetId,omitempty"`
	// Contexte de l’action, variable selon le type.
	Metadata map[string]interface{} `json:"metadata,omitempty" url:"metadata,omitempty"`
	// Non nul si l’action a été faite par le support Mailmus pendant une session d’assistance.
	ImpersonatedByStaffEmail map[string]interface{} `json:"impersonatedByStaffEmail,omitempty" url:"impersonatedByStaffEmail,omitempty"`
	CreatedAt                time.Time              `json:"createdAt" url:"createdAt"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (a *AuditLogEntryResponseDto) GetID() string {
	if a == nil {
		return ""
	}
	return a.ID
}

func (a *AuditLogEntryResponseDto) GetActorEmail() string {
	if a == nil {
		return ""
	}
	return a.ActorEmail
}

func (a *AuditLogEntryResponseDto) GetAction() string {
	if a == nil {
		return ""
	}
	return a.Action
}

func (a *AuditLogEntryResponseDto) GetTargetType() string {
	if a == nil {
		return ""
	}
	return a.TargetType
}

func (a *AuditLogEntryResponseDto) GetTargetID() map[string]interface{} {
	if a == nil {
		return nil
	}
	return a.TargetID
}

func (a *AuditLogEntryResponseDto) GetMetadata() map[string]interface{} {
	if a == nil {
		return nil
	}
	return a.Metadata
}

func (a *AuditLogEntryResponseDto) GetImpersonatedByStaffEmail() map[string]interface{} {
	if a == nil {
		return nil
	}
	return a.ImpersonatedByStaffEmail
}

func (a *AuditLogEntryResponseDto) GetCreatedAt() time.Time {
	if a == nil {
		return time.Time{}
	}
	return a.CreatedAt
}

func (a *AuditLogEntryResponseDto) GetExtraProperties() map[string]interface{} {
	return a.extraProperties
}

func (a *AuditLogEntryResponseDto) UnmarshalJSON(data []byte) error {
	type embed AuditLogEntryResponseDto
	var unmarshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"createdAt"`
	}{
		embed: embed(*a),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*a = AuditLogEntryResponseDto(unmarshaler.embed)
	a.CreatedAt = unmarshaler.CreatedAt.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *a)
	if err != nil {
		return err
	}
	a.extraProperties = extraProperties
	a.rawJSON = json.RawMessage(data)
	return nil
}

func (a *AuditLogEntryResponseDto) MarshalJSON() ([]byte, error) {
	type embed AuditLogEntryResponseDto
	var marshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"createdAt"`
	}{
		embed:     embed(*a),
		CreatedAt: internal.NewDateTime(a.CreatedAt),
	}
	return json.Marshal(marshaler)
}

func (a *AuditLogEntryResponseDto) String() string {
	if len(a.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(a.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(a); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", a)
}

type AuditLogListResponseDto struct {
	Data  []*AuditLogEntryResponseDto `json:"data,omitempty" url:"data,omitempty"`
	Total float64                     `json:"total" url:"total"`
	Page  float64                     `json:"page" url:"page"`
	Pages float64                     `json:"pages" url:"pages"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (a *AuditLogListResponseDto) GetData() []*AuditLogEntryResponseDto {
	if a == nil {
		return nil
	}
	return a.Data
}

func (a *AuditLogListResponseDto) GetTotal() float64 {
	if a == nil {
		return 0
	}
	return a.Total
}

func (a *AuditLogListResponseDto) GetPage() float64 {
	if a == nil {
		return 0
	}
	return a.Page
}

func (a *AuditLogListResponseDto) GetPages() float64 {
	if a == nil {
		return 0
	}
	return a.Pages
}

func (a *AuditLogListResponseDto) GetExtraProperties() map[string]interface{} {
	return a.extraProperties
}

func (a *AuditLogListResponseDto) UnmarshalJSON(data []byte) error {
	type unmarshaler AuditLogListResponseDto
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*a = AuditLogListResponseDto(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *a)
	if err != nil {
		return err
	}
	a.extraProperties = extraProperties
	a.rawJSON = json.RawMessage(data)
	return nil
}

func (a *AuditLogListResponseDto) String() string {
	if len(a.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(a.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(a); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", a)
}

type CustomerIdentityResponseDto struct {
	Provider  CustomerIdentityResponseDtoProvider `json:"provider" url:"provider"`
	CreatedAt time.Time                           `json:"createdAt" url:"createdAt"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CustomerIdentityResponseDto) GetProvider() CustomerIdentityResponseDtoProvider {
	if c == nil {
		return ""
	}
	return c.Provider
}

func (c *CustomerIdentityResponseDto) GetCreatedAt() time.Time {
	if c == nil {
		return time.Time{}
	}
	return c.CreatedAt
}

func (c *CustomerIdentityResponseDto) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CustomerIdentityResponseDto) UnmarshalJSON(data []byte) error {
	type embed CustomerIdentityResponseDto
	var unmarshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"createdAt"`
	}{
		embed: embed(*c),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*c = CustomerIdentityResponseDto(unmarshaler.embed)
	c.CreatedAt = unmarshaler.CreatedAt.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CustomerIdentityResponseDto) MarshalJSON() ([]byte, error) {
	type embed CustomerIdentityResponseDto
	var marshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"createdAt"`
	}{
		embed:     embed(*c),
		CreatedAt: internal.NewDateTime(c.CreatedAt),
	}
	return json.Marshal(marshaler)
}

func (c *CustomerIdentityResponseDto) String() string {
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

type CustomerIdentityResponseDtoProvider string

const (
	CustomerIdentityResponseDtoProviderPassword  CustomerIdentityResponseDtoProvider = "PASSWORD"
	CustomerIdentityResponseDtoProviderEmailCode CustomerIdentityResponseDtoProvider = "EMAIL_CODE"
	CustomerIdentityResponseDtoProviderPhoneCode CustomerIdentityResponseDtoProvider = "PHONE_CODE"
	CustomerIdentityResponseDtoProviderGoogle    CustomerIdentityResponseDtoProvider = "GOOGLE"
	CustomerIdentityResponseDtoProviderGithub    CustomerIdentityResponseDtoProvider = "GITHUB"
	CustomerIdentityResponseDtoProviderApple     CustomerIdentityResponseDtoProvider = "APPLE"
	CustomerIdentityResponseDtoProviderSAML      CustomerIdentityResponseDtoProvider = "SAML"
)

func NewCustomerIdentityResponseDtoProviderFromString(s string) (CustomerIdentityResponseDtoProvider, error) {
	switch s {
	case "PASSWORD":
		return CustomerIdentityResponseDtoProviderPassword, nil
	case "EMAIL_CODE":
		return CustomerIdentityResponseDtoProviderEmailCode, nil
	case "PHONE_CODE":
		return CustomerIdentityResponseDtoProviderPhoneCode, nil
	case "GOOGLE":
		return CustomerIdentityResponseDtoProviderGoogle, nil
	case "GITHUB":
		return CustomerIdentityResponseDtoProviderGithub, nil
	case "APPLE":
		return CustomerIdentityResponseDtoProviderApple, nil
	case "SAML":
		return CustomerIdentityResponseDtoProviderSAML, nil
	}
	var t CustomerIdentityResponseDtoProvider
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CustomerIdentityResponseDtoProvider) Ptr() *CustomerIdentityResponseDtoProvider {
	return &c
}

type CustomerListResponseDto struct {
	Data  []*CustomerResponseDto `json:"data,omitempty" url:"data,omitempty"`
	Total float64                `json:"total" url:"total"`
	Page  float64                `json:"page" url:"page"`
	Pages float64                `json:"pages" url:"pages"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CustomerListResponseDto) GetData() []*CustomerResponseDto {
	if c == nil {
		return nil
	}
	return c.Data
}

func (c *CustomerListResponseDto) GetTotal() float64 {
	if c == nil {
		return 0
	}
	return c.Total
}

func (c *CustomerListResponseDto) GetPage() float64 {
	if c == nil {
		return 0
	}
	return c.Page
}

func (c *CustomerListResponseDto) GetPages() float64 {
	if c == nil {
		return 0
	}
	return c.Pages
}

func (c *CustomerListResponseDto) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CustomerListResponseDto) UnmarshalJSON(data []byte) error {
	type unmarshaler CustomerListResponseDto
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CustomerListResponseDto(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CustomerListResponseDto) String() string {
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

type CustomerResponseDto struct {
	ID              string                 `json:"id" url:"id"`
	ProjectID       string                 `json:"projectId" url:"projectId"`
	Email           *string                `json:"email,omitempty" url:"email,omitempty"`
	EmailVerifiedAt *time.Time             `json:"emailVerifiedAt,omitempty" url:"emailVerifiedAt,omitempty"`
	Phone           *string                `json:"phone,omitempty" url:"phone,omitempty"`
	PhoneVerifiedAt *time.Time             `json:"phoneVerifiedAt,omitempty" url:"phoneVerifiedAt,omitempty"`
	Metadata        map[string]interface{} `json:"metadata,omitempty" url:"metadata,omitempty"`
	Roles           []string               `json:"roles,omitempty" url:"roles,omitempty"`
	LastSignInAt    *time.Time             `json:"lastSignInAt,omitempty" url:"lastSignInAt,omitempty"`
	BannedAt        *time.Time             `json:"bannedAt,omitempty" url:"bannedAt,omitempty"`
	CreatedAt       time.Time              `json:"createdAt" url:"createdAt"`
	UpdatedAt       time.Time              `json:"updatedAt" url:"updatedAt"`
	MfaEnabledAt    *time.Time             `json:"mfaEnabledAt,omitempty" url:"mfaEnabledAt,omitempty"`
	// Tentatives de connexion échouées consécutives (verrou anti-brute-force, remis à zéro sur connexion réussie).
	FailedSignInAttempts float64 `json:"failedSignInAttempts" url:"failedSignInAttempts"`
	// Compte verrouillé jusqu'à cette date (brute-force sur le mot de passe).
	SignInLockedUntil *time.Time                     `json:"signInLockedUntil,omitempty" url:"signInLockedUntil,omitempty"`
	Identities        []*CustomerIdentityResponseDto `json:"identities,omitempty" url:"identities,omitempty"`
	// Sessions actives — présent uniquement sur GET /customers/:id.
	Sessions []*CustomerSessionResponseDto `json:"sessions,omitempty" url:"sessions,omitempty"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CustomerResponseDto) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *CustomerResponseDto) GetProjectID() string {
	if c == nil {
		return ""
	}
	return c.ProjectID
}

func (c *CustomerResponseDto) GetEmail() *string {
	if c == nil {
		return nil
	}
	return c.Email
}

func (c *CustomerResponseDto) GetEmailVerifiedAt() *time.Time {
	if c == nil {
		return nil
	}
	return c.EmailVerifiedAt
}

func (c *CustomerResponseDto) GetPhone() *string {
	if c == nil {
		return nil
	}
	return c.Phone
}

func (c *CustomerResponseDto) GetPhoneVerifiedAt() *time.Time {
	if c == nil {
		return nil
	}
	return c.PhoneVerifiedAt
}

func (c *CustomerResponseDto) GetMetadata() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.Metadata
}

func (c *CustomerResponseDto) GetRoles() []string {
	if c == nil {
		return nil
	}
	return c.Roles
}

func (c *CustomerResponseDto) GetLastSignInAt() *time.Time {
	if c == nil {
		return nil
	}
	return c.LastSignInAt
}

func (c *CustomerResponseDto) GetBannedAt() *time.Time {
	if c == nil {
		return nil
	}
	return c.BannedAt
}

func (c *CustomerResponseDto) GetCreatedAt() time.Time {
	if c == nil {
		return time.Time{}
	}
	return c.CreatedAt
}

func (c *CustomerResponseDto) GetUpdatedAt() time.Time {
	if c == nil {
		return time.Time{}
	}
	return c.UpdatedAt
}

func (c *CustomerResponseDto) GetMfaEnabledAt() *time.Time {
	if c == nil {
		return nil
	}
	return c.MfaEnabledAt
}

func (c *CustomerResponseDto) GetFailedSignInAttempts() float64 {
	if c == nil {
		return 0
	}
	return c.FailedSignInAttempts
}

func (c *CustomerResponseDto) GetSignInLockedUntil() *time.Time {
	if c == nil {
		return nil
	}
	return c.SignInLockedUntil
}

func (c *CustomerResponseDto) GetIdentities() []*CustomerIdentityResponseDto {
	if c == nil {
		return nil
	}
	return c.Identities
}

func (c *CustomerResponseDto) GetSessions() []*CustomerSessionResponseDto {
	if c == nil {
		return nil
	}
	return c.Sessions
}

func (c *CustomerResponseDto) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CustomerResponseDto) UnmarshalJSON(data []byte) error {
	type embed CustomerResponseDto
	var unmarshaler = struct {
		embed
		EmailVerifiedAt   *internal.DateTime `json:"emailVerifiedAt,omitempty"`
		PhoneVerifiedAt   *internal.DateTime `json:"phoneVerifiedAt,omitempty"`
		LastSignInAt      *internal.DateTime `json:"lastSignInAt,omitempty"`
		BannedAt          *internal.DateTime `json:"bannedAt,omitempty"`
		CreatedAt         *internal.DateTime `json:"createdAt"`
		UpdatedAt         *internal.DateTime `json:"updatedAt"`
		MfaEnabledAt      *internal.DateTime `json:"mfaEnabledAt,omitempty"`
		SignInLockedUntil *internal.DateTime `json:"signInLockedUntil,omitempty"`
	}{
		embed: embed(*c),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*c = CustomerResponseDto(unmarshaler.embed)
	c.EmailVerifiedAt = unmarshaler.EmailVerifiedAt.TimePtr()
	c.PhoneVerifiedAt = unmarshaler.PhoneVerifiedAt.TimePtr()
	c.LastSignInAt = unmarshaler.LastSignInAt.TimePtr()
	c.BannedAt = unmarshaler.BannedAt.TimePtr()
	c.CreatedAt = unmarshaler.CreatedAt.Time()
	c.UpdatedAt = unmarshaler.UpdatedAt.Time()
	c.MfaEnabledAt = unmarshaler.MfaEnabledAt.TimePtr()
	c.SignInLockedUntil = unmarshaler.SignInLockedUntil.TimePtr()
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CustomerResponseDto) MarshalJSON() ([]byte, error) {
	type embed CustomerResponseDto
	var marshaler = struct {
		embed
		EmailVerifiedAt   *internal.DateTime `json:"emailVerifiedAt,omitempty"`
		PhoneVerifiedAt   *internal.DateTime `json:"phoneVerifiedAt,omitempty"`
		LastSignInAt      *internal.DateTime `json:"lastSignInAt,omitempty"`
		BannedAt          *internal.DateTime `json:"bannedAt,omitempty"`
		CreatedAt         *internal.DateTime `json:"createdAt"`
		UpdatedAt         *internal.DateTime `json:"updatedAt"`
		MfaEnabledAt      *internal.DateTime `json:"mfaEnabledAt,omitempty"`
		SignInLockedUntil *internal.DateTime `json:"signInLockedUntil,omitempty"`
	}{
		embed:             embed(*c),
		EmailVerifiedAt:   internal.NewOptionalDateTime(c.EmailVerifiedAt),
		PhoneVerifiedAt:   internal.NewOptionalDateTime(c.PhoneVerifiedAt),
		LastSignInAt:      internal.NewOptionalDateTime(c.LastSignInAt),
		BannedAt:          internal.NewOptionalDateTime(c.BannedAt),
		CreatedAt:         internal.NewDateTime(c.CreatedAt),
		UpdatedAt:         internal.NewDateTime(c.UpdatedAt),
		MfaEnabledAt:      internal.NewOptionalDateTime(c.MfaEnabledAt),
		SignInLockedUntil: internal.NewOptionalDateTime(c.SignInLockedUntil),
	}
	return json.Marshal(marshaler)
}

func (c *CustomerResponseDto) String() string {
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

type CustomerSessionResponseDto struct {
	ID        string    `json:"id" url:"id"`
	UserAgent *string   `json:"userAgent,omitempty" url:"userAgent,omitempty"`
	IPAddress *string   `json:"ipAddress,omitempty" url:"ipAddress,omitempty"`
	CreatedAt time.Time `json:"createdAt" url:"createdAt"`
	ExpiresAt time.Time `json:"expiresAt" url:"expiresAt"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CustomerSessionResponseDto) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *CustomerSessionResponseDto) GetUserAgent() *string {
	if c == nil {
		return nil
	}
	return c.UserAgent
}

func (c *CustomerSessionResponseDto) GetIPAddress() *string {
	if c == nil {
		return nil
	}
	return c.IPAddress
}

func (c *CustomerSessionResponseDto) GetCreatedAt() time.Time {
	if c == nil {
		return time.Time{}
	}
	return c.CreatedAt
}

func (c *CustomerSessionResponseDto) GetExpiresAt() time.Time {
	if c == nil {
		return time.Time{}
	}
	return c.ExpiresAt
}

func (c *CustomerSessionResponseDto) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CustomerSessionResponseDto) UnmarshalJSON(data []byte) error {
	type embed CustomerSessionResponseDto
	var unmarshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"createdAt"`
		ExpiresAt *internal.DateTime `json:"expiresAt"`
	}{
		embed: embed(*c),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*c = CustomerSessionResponseDto(unmarshaler.embed)
	c.CreatedAt = unmarshaler.CreatedAt.Time()
	c.ExpiresAt = unmarshaler.ExpiresAt.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CustomerSessionResponseDto) MarshalJSON() ([]byte, error) {
	type embed CustomerSessionResponseDto
	var marshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"createdAt"`
		ExpiresAt *internal.DateTime `json:"expiresAt"`
	}{
		embed:     embed(*c),
		CreatedAt: internal.NewDateTime(c.CreatedAt),
		ExpiresAt: internal.NewDateTime(c.ExpiresAt),
	}
	return json.Marshal(marshaler)
}

func (c *CustomerSessionResponseDto) String() string {
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

type CustomerStatsResponseDto struct {
	Total      float64 `json:"total" url:"total"`
	Verified   float64 `json:"verified" url:"verified"`
	Banned     float64 `json:"banned" url:"banned"`
	MfaEnabled float64 `json:"mfaEnabled" url:"mfaEnabled"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CustomerStatsResponseDto) GetTotal() float64 {
	if c == nil {
		return 0
	}
	return c.Total
}

func (c *CustomerStatsResponseDto) GetVerified() float64 {
	if c == nil {
		return 0
	}
	return c.Verified
}

func (c *CustomerStatsResponseDto) GetBanned() float64 {
	if c == nil {
		return 0
	}
	return c.Banned
}

func (c *CustomerStatsResponseDto) GetMfaEnabled() float64 {
	if c == nil {
		return 0
	}
	return c.MfaEnabled
}

func (c *CustomerStatsResponseDto) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CustomerStatsResponseDto) UnmarshalJSON(data []byte) error {
	type unmarshaler CustomerStatsResponseDto
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CustomerStatsResponseDto(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CustomerStatsResponseDto) String() string {
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}
