// This file was auto-generated by Fern from our API Definition.

package mailmus

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/mailmus/mailmus-go/internal"
)

type VerifyTokenDto struct {
	AccessToken string `json:"accessToken" url:"-"`
}

type VerifiedCustomerResponseDto struct {
	ID               string                 `json:"id" url:"id"`
	Email            *string                `json:"email,omitempty" url:"email,omitempty"`
	Metadata         map[string]interface{} `json:"metadata,omitempty" url:"metadata,omitempty"`
	SessionID        *string                `json:"sessionId,omitempty" url:"sessionId,omitempty"`
	OrganizationID   *string                `json:"organizationId,omitempty" url:"organizationId,omitempty"`
	OrganizationRole *string                `json:"organizationRole,omitempty" url:"organizationRole,omitempty"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (v *VerifiedCustomerResponseDto) GetID() string {
	if v == nil {
		return ""
	}
	return v.ID
}

func (v *VerifiedCustomerResponseDto) GetEmail() *string {
	if v == nil {
		return nil
	}
	return v.Email
}

func (v *VerifiedCustomerResponseDto) GetMetadata() map[string]interface{} {
	if v == nil {
		return nil
	}
	return v.Metadata
}

func (v *VerifiedCustomerResponseDto) GetSessionID() *string {
	if v == nil {
		return nil
	}
	return v.SessionID
}

func (v *VerifiedCustomerResponseDto) GetOrganizationID() *string {
	if v == nil {
		return nil
	}
	return v.OrganizationID
}

func (v *VerifiedCustomerResponseDto) GetOrganizationRole() *string {
	if v == nil {
		return nil
	}
	return v.OrganizationRole
}

func (v *VerifiedCustomerResponseDto) GetExtraProperties() map[string]interface{} {
	return v.extraProperties
}

func (v *VerifiedCustomerResponseDto) UnmarshalJSON(data []byte) error {
	type unmarshaler VerifiedCustomerResponseDto
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*v = VerifiedCustomerResponseDto(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *v)
	if err != nil {
		return err
	}
	v.extraProperties = extraProperties
	v.rawJSON = json.RawMessage(data)
	return nil
}

func (v *VerifiedCustomerResponseDto) String() string {
	if len(v.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(v.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(v); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", v)
}
