// This file was auto-generated by Fern from our API Definition.

package mailmus

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/mailmus/mailmus-go/internal"
)

type TransactionalEmailsControllerLogsRequest struct {
	Status string `json:"-" url:"status"`
	Q      string `json:"-" url:"q"`
}

type TransactionalEmailsControllerSendRequest struct {
	// Replay-safe: a retry with the same key returns the original result instead of sending again.
	IdempotencyKey *string                    `json:"-" url:"-"`
	Body           *SendTransactionalEmailDto `json:"-" url:"-"`
}

func (t *TransactionalEmailsControllerSendRequest) UnmarshalJSON(data []byte) error {
	body := new(SendTransactionalEmailDto)
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	t.Body = body
	return nil
}

func (t *TransactionalEmailsControllerSendRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(t.Body)
}

type SendBatchEmailsDto struct {
	// Max 100 emails per batch.
	Emails []*SendTransactionalEmailDto `json:"emails,omitempty" url:"-"`
}

type EmailAttachmentDto struct {
	Filename string `json:"filename" url:"filename"`
	// Base64-encoded file content
	Content     string  `json:"content" url:"content"`
	ContentType *string `json:"contentType,omitempty" url:"contentType,omitempty"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (e *EmailAttachmentDto) GetFilename() string {
	if e == nil {
		return ""
	}
	return e.Filename
}

func (e *EmailAttachmentDto) GetContent() string {
	if e == nil {
		return ""
	}
	return e.Content
}

func (e *EmailAttachmentDto) GetContentType() *string {
	if e == nil {
		return nil
	}
	return e.ContentType
}

func (e *EmailAttachmentDto) GetExtraProperties() map[string]interface{} {
	return e.extraProperties
}

func (e *EmailAttachmentDto) UnmarshalJSON(data []byte) error {
	type unmarshaler EmailAttachmentDto
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*e = EmailAttachmentDto(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *e)
	if err != nil {
		return err
	}
	e.extraProperties = extraProperties
	e.rawJSON = json.RawMessage(data)
	return nil
}

func (e *EmailAttachmentDto) String() string {
	if len(e.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(e.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(e); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", e)
}

type SendTransactionalEmailDto struct {
	// Primary recipient(s). Accepts a single email or an array.
	To []string `json:"to,omitempty" url:"to,omitempty"`
	// Cc recipient(s). Accepts a single email or an array.
	Cc []string `json:"cc,omitempty" url:"cc,omitempty"`
	// Bcc recipient(s). Accepts a single email or an array.
	Bcc      []string `json:"bcc,omitempty" url:"bcc,omitempty"`
	From     string   `json:"from" url:"from"`
	FromName *string  `json:"fromName,omitempty" url:"fromName,omitempty"`
	ReplyTo  *string  `json:"replyTo,omitempty" url:"replyTo,omitempty"`
	Subject  string   `json:"subject" url:"subject"`
	HTML     *string  `json:"html,omitempty" url:"html,omitempty"`
	// ID of a saved template. Takes precedence over html when both provided.
	TemplateID *string                `json:"templateId,omitempty" url:"templateId,omitempty"`
	Variables  map[string]interface{} `json:"variables,omitempty" url:"variables,omitempty"`
	// Max 10 attachments, 8MB combined (base64-decoded size).
	Attachments []*EmailAttachmentDto `json:"attachments,omitempty" url:"attachments,omitempty"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *SendTransactionalEmailDto) GetTo() []string {
	if s == nil {
		return nil
	}
	return s.To
}

func (s *SendTransactionalEmailDto) GetCc() []string {
	if s == nil {
		return nil
	}
	return s.Cc
}

func (s *SendTransactionalEmailDto) GetBcc() []string {
	if s == nil {
		return nil
	}
	return s.Bcc
}

func (s *SendTransactionalEmailDto) GetFrom() string {
	if s == nil {
		return ""
	}
	return s.From
}

func (s *SendTransactionalEmailDto) GetFromName() *string {
	if s == nil {
		return nil
	}
	return s.FromName
}

func (s *SendTransactionalEmailDto) GetReplyTo() *string {
	if s == nil {
		return nil
	}
	return s.ReplyTo
}

func (s *SendTransactionalEmailDto) GetSubject() string {
	if s == nil {
		return ""
	}
	return s.Subject
}

func (s *SendTransactionalEmailDto) GetHTML() *string {
	if s == nil {
		return nil
	}
	return s.HTML
}

func (s *SendTransactionalEmailDto) GetTemplateID() *string {
	if s == nil {
		return nil
	}
	return s.TemplateID
}

func (s *SendTransactionalEmailDto) GetVariables() map[string]interface{} {
	if s == nil {
		return nil
	}
	return s.Variables
}

func (s *SendTransactionalEmailDto) GetAttachments() []*EmailAttachmentDto {
	if s == nil {
		return nil
	}
	return s.Attachments
}

func (s *SendTransactionalEmailDto) GetExtraProperties() map[string]interface{} {
	return s.extraProperties
}

func (s *SendTransactionalEmailDto) UnmarshalJSON(data []byte) error {
	type unmarshaler SendTransactionalEmailDto
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = SendTransactionalEmailDto(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *SendTransactionalEmailDto) String() string {
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}
