// This file was auto-generated by Fern from our API Definition.

package mailmus

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/mailmus/mailmus-go/internal"
	time "time"
)

type InboundEmailListResponseDto struct {
	Data  []*InboundEmailResponseDto `json:"data,omitempty" url:"data,omitempty"`
	Total float64                    `json:"total" url:"total"`
	Page  float64                    `json:"page" url:"page"`
	Pages float64                    `json:"pages" url:"pages"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (i *InboundEmailListResponseDto) GetData() []*InboundEmailResponseDto {
	if i == nil {
		return nil
	}
	return i.Data
}

func (i *InboundEmailListResponseDto) GetTotal() float64 {
	if i == nil {
		return 0
	}
	return i.Total
}

func (i *InboundEmailListResponseDto) GetPage() float64 {
	if i == nil {
		return 0
	}
	return i.Page
}

func (i *InboundEmailListResponseDto) GetPages() float64 {
	if i == nil {
		return 0
	}
	return i.Pages
}

func (i *InboundEmailListResponseDto) GetExtraProperties() map[string]interface{} {
	return i.extraProperties
}

func (i *InboundEmailListResponseDto) UnmarshalJSON(data []byte) error {
	type unmarshaler InboundEmailListResponseDto
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*i = InboundEmailListResponseDto(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *i)
	if err != nil {
		return err
	}
	i.extraProperties = extraProperties
	i.rawJSON = json.RawMessage(data)
	return nil
}

func (i *InboundEmailListResponseDto) String() string {
	if len(i.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(i.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(i); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", i)
}

type InboundEmailResponseDto struct {
	ID    string `json:"id" url:"id"`
	AppID string `json:"appId" url:"appId"`
	// Identifiant du message chez l’expéditeur.
	MessageID string                 `json:"messageId" url:"messageId"`
	From      string                 `json:"from" url:"from"`
	To        []string               `json:"to,omitempty" url:"to,omitempty"`
	Subject   map[string]interface{} `json:"subject,omitempty" url:"subject,omitempty"`
	TextBody  map[string]interface{} `json:"textBody,omitempty" url:"textBody,omitempty"`
	HTMLBody  map[string]interface{} `json:"htmlBody,omitempty" url:"htmlBody,omitempty"`
	// Pièces jointes, avec leur nom et leur type.
	Attachments map[string]interface{} `json:"attachments,omitempty" url:"attachments,omitempty"`
	// Verdict antispam du fournisseur de réception.
	SpamVerdict map[string]interface{} `json:"spamVerdict,omitempty" url:"spamVerdict,omitempty"`
	ReceivedAt  time.Time              `json:"receivedAt" url:"receivedAt"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (i *InboundEmailResponseDto) GetID() string {
	if i == nil {
		return ""
	}
	return i.ID
}

func (i *InboundEmailResponseDto) GetAppID() string {
	if i == nil {
		return ""
	}
	return i.AppID
}

func (i *InboundEmailResponseDto) GetMessageID() string {
	if i == nil {
		return ""
	}
	return i.MessageID
}

func (i *InboundEmailResponseDto) GetFrom() string {
	if i == nil {
		return ""
	}
	return i.From
}

func (i *InboundEmailResponseDto) GetTo() []string {
	if i == nil {
		return nil
	}
	return i.To
}

func (i *InboundEmailResponseDto) GetSubject() map[string]interface{} {
	if i == nil {
		return nil
	}
	return i.Subject
}

func (i *InboundEmailResponseDto) GetTextBody() map[string]interface{} {
	if i == nil {
		return nil
	}
	return i.TextBody
}

func (i *InboundEmailResponseDto) GetHTMLBody() map[string]interface{} {
	if i == nil {
		return nil
	}
	return i.HTMLBody
}

func (i *InboundEmailResponseDto) GetAttachments() map[string]interface{} {
	if i == nil {
		return nil
	}
	return i.Attachments
}

func (i *InboundEmailResponseDto) GetSpamVerdict() map[string]interface{} {
	if i == nil {
		return nil
	}
	return i.SpamVerdict
}

func (i *InboundEmailResponseDto) GetReceivedAt() time.Time {
	if i == nil {
		return time.Time{}
	}
	return i.ReceivedAt
}

func (i *InboundEmailResponseDto) GetExtraProperties() map[string]interface{} {
	return i.extraProperties
}

func (i *InboundEmailResponseDto) UnmarshalJSON(data []byte) error {
	type embed InboundEmailResponseDto
	var unmarshaler = struct {
		embed
		ReceivedAt *internal.DateTime `json:"receivedAt"`
	}{
		embed: embed(*i),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*i = InboundEmailResponseDto(unmarshaler.embed)
	i.ReceivedAt = unmarshaler.ReceivedAt.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *i)
	if err != nil {
		return err
	}
	i.extraProperties = extraProperties
	i.rawJSON = json.RawMessage(data)
	return nil
}

func (i *InboundEmailResponseDto) MarshalJSON() ([]byte, error) {
	type embed InboundEmailResponseDto
	var marshaler = struct {
		embed
		ReceivedAt *internal.DateTime `json:"receivedAt"`
	}{
		embed:      embed(*i),
		ReceivedAt: internal.NewDateTime(i.ReceivedAt),
	}
	return json.Marshal(marshaler)
}

func (i *InboundEmailResponseDto) String() string {
	if len(i.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(i.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(i); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", i)
}
