// This file was auto-generated by Fern from our API Definition.

package mailmus

import (
	fmt "fmt"
)

type AddMemberDto struct {
	CustomerID string            `json:"customerId" url:"-"`
	Role       *AddMemberDtoRole `json:"role,omitempty" url:"-"`
}

type UpdateMemberRoleDto struct {
	Role UpdateMemberRoleDtoRole `json:"role" url:"-"`
}

type AddMemberDtoRole string

const (
	AddMemberDtoRoleOwner  AddMemberDtoRole = "OWNER"
	AddMemberDtoRoleAdmin  AddMemberDtoRole = "ADMIN"
	AddMemberDtoRoleMember AddMemberDtoRole = "MEMBER"
)

func NewAddMemberDtoRoleFromString(s string) (AddMemberDtoRole, error) {
	switch s {
	case "OWNER":
		return AddMemberDtoRoleOwner, nil
	case "ADMIN":
		return AddMemberDtoRoleAdmin, nil
	case "MEMBER":
		return AddMemberDtoRoleMember, nil
	}
	var t AddMemberDtoRole
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (a AddMemberDtoRole) Ptr() *AddMemberDtoRole {
	return &a
}

type UpdateMemberRoleDtoRole string

const (
	UpdateMemberRoleDtoRoleOwner  UpdateMemberRoleDtoRole = "OWNER"
	UpdateMemberRoleDtoRoleAdmin  UpdateMemberRoleDtoRole = "ADMIN"
	UpdateMemberRoleDtoRoleMember UpdateMemberRoleDtoRole = "MEMBER"
)

func NewUpdateMemberRoleDtoRoleFromString(s string) (UpdateMemberRoleDtoRole, error) {
	switch s {
	case "OWNER":
		return UpdateMemberRoleDtoRoleOwner, nil
	case "ADMIN":
		return UpdateMemberRoleDtoRoleAdmin, nil
	case "MEMBER":
		return UpdateMemberRoleDtoRoleMember, nil
	}
	var t UpdateMemberRoleDtoRole
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (u UpdateMemberRoleDtoRole) Ptr() *UpdateMemberRoleDtoRole {
	return &u
}
