// This file was auto-generated by Fern from our API Definition.

package mailmus

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/mailmus/mailmus-go/internal"
	time "time"
)

type CreateOrganizationDto struct {
	Name string `json:"name" url:"-"`
	// Métadonnées libres définies par le développeur.
	Metadata map[string]interface{} `json:"metadata,omitempty" url:"-"`
}

type OrganizationResponseDto struct {
	ID                     string                 `json:"id" url:"id"`
	ProjectID              string                 `json:"projectId" url:"projectId"`
	Name                   string                 `json:"name" url:"name"`
	Slug                   string                 `json:"slug" url:"slug"`
	Metadata               map[string]interface{} `json:"metadata,omitempty" url:"metadata,omitempty"`
	CreatedAt              time.Time              `json:"createdAt" url:"createdAt"`
	UpdatedAt              time.Time              `json:"updatedAt" url:"updatedAt"`
	MemberCount            *float64               `json:"memberCount,omitempty" url:"memberCount,omitempty"`
	PendingInvitationCount *float64               `json:"pendingInvitationCount,omitempty" url:"pendingInvitationCount,omitempty"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (o *OrganizationResponseDto) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *OrganizationResponseDto) GetProjectID() string {
	if o == nil {
		return ""
	}
	return o.ProjectID
}

func (o *OrganizationResponseDto) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *OrganizationResponseDto) GetSlug() string {
	if o == nil {
		return ""
	}
	return o.Slug
}

func (o *OrganizationResponseDto) GetMetadata() map[string]interface{} {
	if o == nil {
		return nil
	}
	return o.Metadata
}

func (o *OrganizationResponseDto) GetCreatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.CreatedAt
}

func (o *OrganizationResponseDto) GetUpdatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.UpdatedAt
}

func (o *OrganizationResponseDto) GetMemberCount() *float64 {
	if o == nil {
		return nil
	}
	return o.MemberCount
}

func (o *OrganizationResponseDto) GetPendingInvitationCount() *float64 {
	if o == nil {
		return nil
	}
	return o.PendingInvitationCount
}

func (o *OrganizationResponseDto) GetExtraProperties() map[string]interface{} {
	return o.extraProperties
}

func (o *OrganizationResponseDto) UnmarshalJSON(data []byte) error {
	type embed OrganizationResponseDto
	var unmarshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"createdAt"`
		UpdatedAt *internal.DateTime `json:"updatedAt"`
	}{
		embed: embed(*o),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*o = OrganizationResponseDto(unmarshaler.embed)
	o.CreatedAt = unmarshaler.CreatedAt.Time()
	o.UpdatedAt = unmarshaler.UpdatedAt.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *o)
	if err != nil {
		return err
	}
	o.extraProperties = extraProperties
	o.rawJSON = json.RawMessage(data)
	return nil
}

func (o *OrganizationResponseDto) MarshalJSON() ([]byte, error) {
	type embed OrganizationResponseDto
	var marshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"createdAt"`
		UpdatedAt *internal.DateTime `json:"updatedAt"`
	}{
		embed:     embed(*o),
		CreatedAt: internal.NewDateTime(o.CreatedAt),
		UpdatedAt: internal.NewDateTime(o.UpdatedAt),
	}
	return json.Marshal(marshaler)
}

func (o *OrganizationResponseDto) String() string {
	if len(o.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(o.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(o); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", o)
}

type UpdateOrganizationDto struct {
	Name     *string                `json:"name,omitempty" url:"-"`
	Metadata map[string]interface{} `json:"metadata,omitempty" url:"-"`
}
