// This file was auto-generated by Fern from our API Definition.

package mailmus

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/mailmus/mailmus-go/internal"
	time "time"
)

type CreateInvitationDto struct {
	Email string                   `json:"email" url:"-"`
	Role  *CreateInvitationDtoRole `json:"role,omitempty" url:"-"`
}

type OrganizationInvitationsListRequest struct {
	Status string `json:"-" url:"status"`
}

type OrganizationInvitationResponseDto struct {
	ID                  string                                  `json:"id" url:"id"`
	OrganizationID      string                                  `json:"organizationId" url:"organizationId"`
	ProjectID           string                                  `json:"projectId" url:"projectId"`
	Email               string                                  `json:"email" url:"email"`
	Role                OrganizationInvitationResponseDtoRole   `json:"role" url:"role"`
	Status              OrganizationInvitationResponseDtoStatus `json:"status" url:"status"`
	InvitedByCustomerID *string                                 `json:"invitedByCustomerId,omitempty" url:"invitedByCustomerId,omitempty"`
	ExpiresAt           time.Time                               `json:"expiresAt" url:"expiresAt"`
	AcceptedAt          *time.Time                              `json:"acceptedAt,omitempty" url:"acceptedAt,omitempty"`
	RevokedAt           *time.Time                              `json:"revokedAt,omitempty" url:"revokedAt,omitempty"`
	CreatedAt           time.Time                               `json:"createdAt" url:"createdAt"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (o *OrganizationInvitationResponseDto) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *OrganizationInvitationResponseDto) GetOrganizationID() string {
	if o == nil {
		return ""
	}
	return o.OrganizationID
}

func (o *OrganizationInvitationResponseDto) GetProjectID() string {
	if o == nil {
		return ""
	}
	return o.ProjectID
}

func (o *OrganizationInvitationResponseDto) GetEmail() string {
	if o == nil {
		return ""
	}
	return o.Email
}

func (o *OrganizationInvitationResponseDto) GetRole() OrganizationInvitationResponseDtoRole {
	if o == nil {
		return ""
	}
	return o.Role
}

func (o *OrganizationInvitationResponseDto) GetStatus() OrganizationInvitationResponseDtoStatus {
	if o == nil {
		return ""
	}
	return o.Status
}

func (o *OrganizationInvitationResponseDto) GetInvitedByCustomerID() *string {
	if o == nil {
		return nil
	}
	return o.InvitedByCustomerID
}

func (o *OrganizationInvitationResponseDto) GetExpiresAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.ExpiresAt
}

func (o *OrganizationInvitationResponseDto) GetAcceptedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.AcceptedAt
}

func (o *OrganizationInvitationResponseDto) GetRevokedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.RevokedAt
}

func (o *OrganizationInvitationResponseDto) GetCreatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.CreatedAt
}

func (o *OrganizationInvitationResponseDto) GetExtraProperties() map[string]interface{} {
	return o.extraProperties
}

func (o *OrganizationInvitationResponseDto) UnmarshalJSON(data []byte) error {
	type embed OrganizationInvitationResponseDto
	var unmarshaler = struct {
		embed
		ExpiresAt  *internal.DateTime `json:"expiresAt"`
		AcceptedAt *internal.DateTime `json:"acceptedAt,omitempty"`
		RevokedAt  *internal.DateTime `json:"revokedAt,omitempty"`
		CreatedAt  *internal.DateTime `json:"createdAt"`
	}{
		embed: embed(*o),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*o = OrganizationInvitationResponseDto(unmarshaler.embed)
	o.ExpiresAt = unmarshaler.ExpiresAt.Time()
	o.AcceptedAt = unmarshaler.AcceptedAt.TimePtr()
	o.RevokedAt = unmarshaler.RevokedAt.TimePtr()
	o.CreatedAt = unmarshaler.CreatedAt.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *o)
	if err != nil {
		return err
	}
	o.extraProperties = extraProperties
	o.rawJSON = json.RawMessage(data)
	return nil
}

func (o *OrganizationInvitationResponseDto) MarshalJSON() ([]byte, error) {
	type embed OrganizationInvitationResponseDto
	var marshaler = struct {
		embed
		ExpiresAt  *internal.DateTime `json:"expiresAt"`
		AcceptedAt *internal.DateTime `json:"acceptedAt,omitempty"`
		RevokedAt  *internal.DateTime `json:"revokedAt,omitempty"`
		CreatedAt  *internal.DateTime `json:"createdAt"`
	}{
		embed:      embed(*o),
		ExpiresAt:  internal.NewDateTime(o.ExpiresAt),
		AcceptedAt: internal.NewOptionalDateTime(o.AcceptedAt),
		RevokedAt:  internal.NewOptionalDateTime(o.RevokedAt),
		CreatedAt:  internal.NewDateTime(o.CreatedAt),
	}
	return json.Marshal(marshaler)
}

func (o *OrganizationInvitationResponseDto) String() string {
	if len(o.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(o.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(o); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", o)
}

type OrganizationInvitationResponseDtoRole string

const (
	OrganizationInvitationResponseDtoRoleOwner  OrganizationInvitationResponseDtoRole = "OWNER"
	OrganizationInvitationResponseDtoRoleAdmin  OrganizationInvitationResponseDtoRole = "ADMIN"
	OrganizationInvitationResponseDtoRoleMember OrganizationInvitationResponseDtoRole = "MEMBER"
)

func NewOrganizationInvitationResponseDtoRoleFromString(s string) (OrganizationInvitationResponseDtoRole, error) {
	switch s {
	case "OWNER":
		return OrganizationInvitationResponseDtoRoleOwner, nil
	case "ADMIN":
		return OrganizationInvitationResponseDtoRoleAdmin, nil
	case "MEMBER":
		return OrganizationInvitationResponseDtoRoleMember, nil
	}
	var t OrganizationInvitationResponseDtoRole
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (o OrganizationInvitationResponseDtoRole) Ptr() *OrganizationInvitationResponseDtoRole {
	return &o
}

type OrganizationInvitationResponseDtoStatus string

const (
	OrganizationInvitationResponseDtoStatusPending  OrganizationInvitationResponseDtoStatus = "PENDING"
	OrganizationInvitationResponseDtoStatusAccepted OrganizationInvitationResponseDtoStatus = "ACCEPTED"
	OrganizationInvitationResponseDtoStatusRevoked  OrganizationInvitationResponseDtoStatus = "REVOKED"
	OrganizationInvitationResponseDtoStatusExpired  OrganizationInvitationResponseDtoStatus = "EXPIRED"
)

func NewOrganizationInvitationResponseDtoStatusFromString(s string) (OrganizationInvitationResponseDtoStatus, error) {
	switch s {
	case "PENDING":
		return OrganizationInvitationResponseDtoStatusPending, nil
	case "ACCEPTED":
		return OrganizationInvitationResponseDtoStatusAccepted, nil
	case "REVOKED":
		return OrganizationInvitationResponseDtoStatusRevoked, nil
	case "EXPIRED":
		return OrganizationInvitationResponseDtoStatusExpired, nil
	}
	var t OrganizationInvitationResponseDtoStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (o OrganizationInvitationResponseDtoStatus) Ptr() *OrganizationInvitationResponseDtoStatus {
	return &o
}

type CreateInvitationDtoRole string

const (
	CreateInvitationDtoRoleOwner  CreateInvitationDtoRole = "OWNER"
	CreateInvitationDtoRoleAdmin  CreateInvitationDtoRole = "ADMIN"
	CreateInvitationDtoRoleMember CreateInvitationDtoRole = "MEMBER"
)

func NewCreateInvitationDtoRoleFromString(s string) (CreateInvitationDtoRole, error) {
	switch s {
	case "OWNER":
		return CreateInvitationDtoRoleOwner, nil
	case "ADMIN":
		return CreateInvitationDtoRoleAdmin, nil
	case "MEMBER":
		return CreateInvitationDtoRoleMember, nil
	}
	var t CreateInvitationDtoRole
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CreateInvitationDtoRole) Ptr() *CreateInvitationDtoRole {
	return &c
}
