// This file was auto-generated by Fern from our API Definition.

package mailmus

type PublicSignupDto struct {
	PublishableKey string                 `json:"publishableKey" url:"-"`
	AudienceID     string                 `json:"audienceId" url:"-"`
	Email          string                 `json:"email" url:"-"`
	Attributes     map[string]interface{} `json:"attributes,omitempty" url:"-"`
}
