// This file was auto-generated by Fern from our API Definition.

package mailmus

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/mailmus/mailmus-go/internal"
	time "time"
)

type CreateSeedListEntryDto struct {
	Email string  `json:"email" url:"-"`
	Label *string `json:"label,omitempty" url:"-"`
}

type SeedListEntryResponseDto struct {
	ID    string `json:"id" url:"id"`
	AppID string `json:"appId" url:"appId"`
	Email string `json:"email" url:"email"`
	// Repère libre, par exemple le fournisseur testé.
	Label     map[string]interface{} `json:"label,omitempty" url:"label,omitempty"`
	CreatedAt time.Time              `json:"createdAt" url:"createdAt"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *SeedListEntryResponseDto) GetID() string {
	if s == nil {
		return ""
	}
	return s.ID
}

func (s *SeedListEntryResponseDto) GetAppID() string {
	if s == nil {
		return ""
	}
	return s.AppID
}

func (s *SeedListEntryResponseDto) GetEmail() string {
	if s == nil {
		return ""
	}
	return s.Email
}

func (s *SeedListEntryResponseDto) GetLabel() map[string]interface{} {
	if s == nil {
		return nil
	}
	return s.Label
}

func (s *SeedListEntryResponseDto) GetCreatedAt() time.Time {
	if s == nil {
		return time.Time{}
	}
	return s.CreatedAt
}

func (s *SeedListEntryResponseDto) GetExtraProperties() map[string]interface{} {
	return s.extraProperties
}

func (s *SeedListEntryResponseDto) UnmarshalJSON(data []byte) error {
	type embed SeedListEntryResponseDto
	var unmarshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"createdAt"`
	}{
		embed: embed(*s),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*s = SeedListEntryResponseDto(unmarshaler.embed)
	s.CreatedAt = unmarshaler.CreatedAt.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *SeedListEntryResponseDto) MarshalJSON() ([]byte, error) {
	type embed SeedListEntryResponseDto
	var marshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"createdAt"`
	}{
		embed:     embed(*s),
		CreatedAt: internal.NewDateTime(s.CreatedAt),
	}
	return json.Marshal(marshaler)
}

func (s *SeedListEntryResponseDto) String() string {
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}
