// This file was auto-generated by Fern from our API Definition.

package mailmus

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/mailmus/mailmus-go/internal"
	time "time"
)

type CreateSSOConnectionDto struct {
	Name string `json:"name" url:"-"`
	// Domaine email des employés de l'organisation cliente — utilisé pour le Home Realm Discovery (redirection automatique vers l'IdP au sign-in).
	Domain string `json:"domain" url:"-"`
}

type UpdateSSOConnectionDto struct {
	Name   *string `json:"name,omitempty" url:"-"`
	Domain *string `json:"domain,omitempty" url:"-"`
	// Entity ID de l'IdP (Issuer), fourni par Okta/Azure AD/etc.
	IdpEntityID *string `json:"idpEntityId,omitempty" url:"-"`
	// URL SSO (SingleSignOnService) de l'IdP.
	IdpSsoUrl *string `json:"idpSsoUrl,omitempty" url:"-"`
	// Certificat(s) X.509 de signature de l'IdP, en PEM. Tableau pour permettre une rotation sans coupure.
	IdpCertificate []string `json:"idpCertificate,omitempty" url:"-"`
}

type SSOConnectionResponseDto struct {
	ID             string                         `json:"id" url:"id"`
	OrganizationID string                         `json:"organizationId" url:"organizationId"`
	ProjectID      string                         `json:"projectId" url:"projectId"`
	Name           string                         `json:"name" url:"name"`
	Domain         string                         `json:"domain" url:"domain"`
	Status         SSOConnectionResponseDtoStatus `json:"status" url:"status"`
	IdpEntityID    *string                        `json:"idpEntityId,omitempty" url:"idpEntityId,omitempty"`
	IdpSsoUrl      *string                        `json:"idpSsoUrl,omitempty" url:"idpSsoUrl,omitempty"`
	IdpCertificate []string                       `json:"idpCertificate,omitempty" url:"idpCertificate,omitempty"`
	SpCertificate  string                         `json:"spCertificate" url:"spCertificate"`
	CreatedAt      time.Time                      `json:"createdAt" url:"createdAt"`
	UpdatedAt      time.Time                      `json:"updatedAt" url:"updatedAt"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *SSOConnectionResponseDto) GetID() string {
	if s == nil {
		return ""
	}
	return s.ID
}

func (s *SSOConnectionResponseDto) GetOrganizationID() string {
	if s == nil {
		return ""
	}
	return s.OrganizationID
}

func (s *SSOConnectionResponseDto) GetProjectID() string {
	if s == nil {
		return ""
	}
	return s.ProjectID
}

func (s *SSOConnectionResponseDto) GetName() string {
	if s == nil {
		return ""
	}
	return s.Name
}

func (s *SSOConnectionResponseDto) GetDomain() string {
	if s == nil {
		return ""
	}
	return s.Domain
}

func (s *SSOConnectionResponseDto) GetStatus() SSOConnectionResponseDtoStatus {
	if s == nil {
		return ""
	}
	return s.Status
}

func (s *SSOConnectionResponseDto) GetIdpEntityID() *string {
	if s == nil {
		return nil
	}
	return s.IdpEntityID
}

func (s *SSOConnectionResponseDto) GetIdpSsoUrl() *string {
	if s == nil {
		return nil
	}
	return s.IdpSsoUrl
}

func (s *SSOConnectionResponseDto) GetIdpCertificate() []string {
	if s == nil {
		return nil
	}
	return s.IdpCertificate
}

func (s *SSOConnectionResponseDto) GetSpCertificate() string {
	if s == nil {
		return ""
	}
	return s.SpCertificate
}

func (s *SSOConnectionResponseDto) GetCreatedAt() time.Time {
	if s == nil {
		return time.Time{}
	}
	return s.CreatedAt
}

func (s *SSOConnectionResponseDto) GetUpdatedAt() time.Time {
	if s == nil {
		return time.Time{}
	}
	return s.UpdatedAt
}

func (s *SSOConnectionResponseDto) GetExtraProperties() map[string]interface{} {
	return s.extraProperties
}

func (s *SSOConnectionResponseDto) UnmarshalJSON(data []byte) error {
	type embed SSOConnectionResponseDto
	var unmarshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"createdAt"`
		UpdatedAt *internal.DateTime `json:"updatedAt"`
	}{
		embed: embed(*s),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*s = SSOConnectionResponseDto(unmarshaler.embed)
	s.CreatedAt = unmarshaler.CreatedAt.Time()
	s.UpdatedAt = unmarshaler.UpdatedAt.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *SSOConnectionResponseDto) MarshalJSON() ([]byte, error) {
	type embed SSOConnectionResponseDto
	var marshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"createdAt"`
		UpdatedAt *internal.DateTime `json:"updatedAt"`
	}{
		embed:     embed(*s),
		CreatedAt: internal.NewDateTime(s.CreatedAt),
		UpdatedAt: internal.NewDateTime(s.UpdatedAt),
	}
	return json.Marshal(marshaler)
}

func (s *SSOConnectionResponseDto) String() string {
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

type SSOConnectionResponseDtoStatus string

const (
	SSOConnectionResponseDtoStatusDraft    SSOConnectionResponseDtoStatus = "DRAFT"
	SSOConnectionResponseDtoStatusActive   SSOConnectionResponseDtoStatus = "ACTIVE"
	SSOConnectionResponseDtoStatusDisabled SSOConnectionResponseDtoStatus = "DISABLED"
)

func NewSSOConnectionResponseDtoStatusFromString(s string) (SSOConnectionResponseDtoStatus, error) {
	switch s {
	case "DRAFT":
		return SSOConnectionResponseDtoStatusDraft, nil
	case "ACTIVE":
		return SSOConnectionResponseDtoStatusActive, nil
	case "DISABLED":
		return SSOConnectionResponseDtoStatusDisabled, nil
	}
	var t SSOConnectionResponseDtoStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (s SSOConnectionResponseDtoStatus) Ptr() *SSOConnectionResponseDtoStatus {
	return &s
}
