// This file was auto-generated by Fern from our API Definition.

package mailmus

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/mailmus/mailmus-go/internal"
)

type PlatformStatusResponseDto struct {
	Services []*ServiceStatusDto `json:"services,omitempty" url:"services,omitempty"`
	// Longueur de la fenêtre de disponibilité, en jours.
	UptimeWindowDays float64 `json:"uptimeWindowDays" url:"uptimeWindowDays"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *PlatformStatusResponseDto) GetServices() []*ServiceStatusDto {
	if p == nil {
		return nil
	}
	return p.Services
}

func (p *PlatformStatusResponseDto) GetUptimeWindowDays() float64 {
	if p == nil {
		return 0
	}
	return p.UptimeWindowDays
}

func (p *PlatformStatusResponseDto) GetExtraProperties() map[string]interface{} {
	return p.extraProperties
}

func (p *PlatformStatusResponseDto) UnmarshalJSON(data []byte) error {
	type unmarshaler PlatformStatusResponseDto
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = PlatformStatusResponseDto(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *PlatformStatusResponseDto) String() string {
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

type ServiceStatusDto struct {
	Service ServiceStatusDtoService `json:"service" url:"service"`
	// Résultat du dernier contrôle. Nul si aucun n’a encore eu lieu.
	IsUp           map[string]interface{} `json:"isUp,omitempty" url:"isUp,omitempty"`
	CheckedAt      map[string]interface{} `json:"checkedAt,omitempty" url:"checkedAt,omitempty"`
	ResponseTimeMs map[string]interface{} `json:"responseTimeMs,omitempty" url:"responseTimeMs,omitempty"`
	// Disponibilité en pourcentage, à une décimale.
	UptimePercent30D map[string]interface{} `json:"uptimePercent30d,omitempty" url:"uptimePercent30d,omitempty"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *ServiceStatusDto) GetService() ServiceStatusDtoService {
	if s == nil {
		return ""
	}
	return s.Service
}

func (s *ServiceStatusDto) GetIsUp() map[string]interface{} {
	if s == nil {
		return nil
	}
	return s.IsUp
}

func (s *ServiceStatusDto) GetCheckedAt() map[string]interface{} {
	if s == nil {
		return nil
	}
	return s.CheckedAt
}

func (s *ServiceStatusDto) GetResponseTimeMs() map[string]interface{} {
	if s == nil {
		return nil
	}
	return s.ResponseTimeMs
}

func (s *ServiceStatusDto) GetUptimePercent30D() map[string]interface{} {
	if s == nil {
		return nil
	}
	return s.UptimePercent30D
}

func (s *ServiceStatusDto) GetExtraProperties() map[string]interface{} {
	return s.extraProperties
}

func (s *ServiceStatusDto) UnmarshalJSON(data []byte) error {
	type unmarshaler ServiceStatusDto
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = ServiceStatusDto(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *ServiceStatusDto) String() string {
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

type ServiceStatusDtoService string

const (
	ServiceStatusDtoServiceAPI       ServiceStatusDtoService = "api"
	ServiceStatusDtoServiceDashboard ServiceStatusDtoService = "dashboard"
)

func NewServiceStatusDtoServiceFromString(s string) (ServiceStatusDtoService, error) {
	switch s {
	case "api":
		return ServiceStatusDtoServiceAPI, nil
	case "dashboard":
		return ServiceStatusDtoServiceDashboard, nil
	}
	var t ServiceStatusDtoService
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (s ServiceStatusDtoService) Ptr() *ServiceStatusDtoService {
	return &s
}
