// This file was auto-generated by Fern from our API Definition.

package mailmus

type CreateTemplateDto struct {
	Name        string                 `json:"name" url:"-"`
	BuilderJSON map[string]interface{} `json:"builderJson,omitempty" url:"-"`
	HTML        string                 `json:"html" url:"-"`
}

type UpdateTemplateDto struct {
	Name        string                 `json:"name" url:"-"`
	BuilderJSON map[string]interface{} `json:"builderJson,omitempty" url:"-"`
	HTML        string                 `json:"html" url:"-"`
}
