// This file was auto-generated by Fern from our API Definition.

package mailmus

type TrackingControllerClickRequest struct {
	U string `json:"-" url:"u"`
	S string `json:"-" url:"s"`
}

type TrackingControllerUnsubscribeRequest struct {
	S string `json:"-" url:"s"`
}

type TrackingControllerUnsubscribeOneClickRequest struct {
	S string `json:"-" url:"s"`
}
