// This file was auto-generated by Fern from our API Definition.

package mailmus

import (
	fmt "fmt"
)

type CreateWebhookDto struct {
	URL    string                       `json:"url" url:"-"`
	Events []CreateWebhookDtoEventsItem `json:"events,omitempty" url:"-"`
}

type UpdateWebhookDto struct {
	URL    *string                      `json:"url,omitempty" url:"-"`
	Events []UpdateWebhookDtoEventsItem `json:"events,omitempty" url:"-"`
	Active *bool                        `json:"active,omitempty" url:"-"`
}

type CreateWebhookDtoEventsItem string

const (
	CreateWebhookDtoEventsItemContactCreated      CreateWebhookDtoEventsItem = "contact.created"
	CreateWebhookDtoEventsItemContactUnsubscribed CreateWebhookDtoEventsItem = "contact.unsubscribed"
	CreateWebhookDtoEventsItemEmailSent           CreateWebhookDtoEventsItem = "email.sent"
	CreateWebhookDtoEventsItemSendDelivered       CreateWebhookDtoEventsItem = "send.delivered"
	CreateWebhookDtoEventsItemSendBounced         CreateWebhookDtoEventsItem = "send.bounced"
	CreateWebhookDtoEventsItemSendComplained      CreateWebhookDtoEventsItem = "send.complained"
	CreateWebhookDtoEventsItemSendOpened          CreateWebhookDtoEventsItem = "send.opened"
	CreateWebhookDtoEventsItemSendClicked         CreateWebhookDtoEventsItem = "send.clicked"
	CreateWebhookDtoEventsItemCampaignSent        CreateWebhookDtoEventsItem = "campaign.sent"
	CreateWebhookDtoEventsItemDomainVerified      CreateWebhookDtoEventsItem = "domain.verified"
	CreateWebhookDtoEventsItemDomainFailed        CreateWebhookDtoEventsItem = "domain.failed"
	CreateWebhookDtoEventsItemAutomationCompleted CreateWebhookDtoEventsItem = "automation.completed"
	CreateWebhookDtoEventsItemAutomationFailed    CreateWebhookDtoEventsItem = "automation.failed"
)

func NewCreateWebhookDtoEventsItemFromString(s string) (CreateWebhookDtoEventsItem, error) {
	switch s {
	case "contact.created":
		return CreateWebhookDtoEventsItemContactCreated, nil
	case "contact.unsubscribed":
		return CreateWebhookDtoEventsItemContactUnsubscribed, nil
	case "email.sent":
		return CreateWebhookDtoEventsItemEmailSent, nil
	case "send.delivered":
		return CreateWebhookDtoEventsItemSendDelivered, nil
	case "send.bounced":
		return CreateWebhookDtoEventsItemSendBounced, nil
	case "send.complained":
		return CreateWebhookDtoEventsItemSendComplained, nil
	case "send.opened":
		return CreateWebhookDtoEventsItemSendOpened, nil
	case "send.clicked":
		return CreateWebhookDtoEventsItemSendClicked, nil
	case "campaign.sent":
		return CreateWebhookDtoEventsItemCampaignSent, nil
	case "domain.verified":
		return CreateWebhookDtoEventsItemDomainVerified, nil
	case "domain.failed":
		return CreateWebhookDtoEventsItemDomainFailed, nil
	case "automation.completed":
		return CreateWebhookDtoEventsItemAutomationCompleted, nil
	case "automation.failed":
		return CreateWebhookDtoEventsItemAutomationFailed, nil
	}
	var t CreateWebhookDtoEventsItem
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CreateWebhookDtoEventsItem) Ptr() *CreateWebhookDtoEventsItem {
	return &c
}

type UpdateWebhookDtoEventsItem string

const (
	UpdateWebhookDtoEventsItemContactCreated      UpdateWebhookDtoEventsItem = "contact.created"
	UpdateWebhookDtoEventsItemContactUnsubscribed UpdateWebhookDtoEventsItem = "contact.unsubscribed"
	UpdateWebhookDtoEventsItemEmailSent           UpdateWebhookDtoEventsItem = "email.sent"
	UpdateWebhookDtoEventsItemSendDelivered       UpdateWebhookDtoEventsItem = "send.delivered"
	UpdateWebhookDtoEventsItemSendBounced         UpdateWebhookDtoEventsItem = "send.bounced"
	UpdateWebhookDtoEventsItemSendComplained      UpdateWebhookDtoEventsItem = "send.complained"
	UpdateWebhookDtoEventsItemSendOpened          UpdateWebhookDtoEventsItem = "send.opened"
	UpdateWebhookDtoEventsItemSendClicked         UpdateWebhookDtoEventsItem = "send.clicked"
	UpdateWebhookDtoEventsItemCampaignSent        UpdateWebhookDtoEventsItem = "campaign.sent"
	UpdateWebhookDtoEventsItemDomainVerified      UpdateWebhookDtoEventsItem = "domain.verified"
	UpdateWebhookDtoEventsItemDomainFailed        UpdateWebhookDtoEventsItem = "domain.failed"
	UpdateWebhookDtoEventsItemAutomationCompleted UpdateWebhookDtoEventsItem = "automation.completed"
	UpdateWebhookDtoEventsItemAutomationFailed    UpdateWebhookDtoEventsItem = "automation.failed"
)

func NewUpdateWebhookDtoEventsItemFromString(s string) (UpdateWebhookDtoEventsItem, error) {
	switch s {
	case "contact.created":
		return UpdateWebhookDtoEventsItemContactCreated, nil
	case "contact.unsubscribed":
		return UpdateWebhookDtoEventsItemContactUnsubscribed, nil
	case "email.sent":
		return UpdateWebhookDtoEventsItemEmailSent, nil
	case "send.delivered":
		return UpdateWebhookDtoEventsItemSendDelivered, nil
	case "send.bounced":
		return UpdateWebhookDtoEventsItemSendBounced, nil
	case "send.complained":
		return UpdateWebhookDtoEventsItemSendComplained, nil
	case "send.opened":
		return UpdateWebhookDtoEventsItemSendOpened, nil
	case "send.clicked":
		return UpdateWebhookDtoEventsItemSendClicked, nil
	case "campaign.sent":
		return UpdateWebhookDtoEventsItemCampaignSent, nil
	case "domain.verified":
		return UpdateWebhookDtoEventsItemDomainVerified, nil
	case "domain.failed":
		return UpdateWebhookDtoEventsItemDomainFailed, nil
	case "automation.completed":
		return UpdateWebhookDtoEventsItemAutomationCompleted, nil
	case "automation.failed":
		return UpdateWebhookDtoEventsItemAutomationFailed, nil
	}
	var t UpdateWebhookDtoEventsItem
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (u UpdateWebhookDtoEventsItem) Ptr() *UpdateWebhookDtoEventsItem {
	return &u
}
