// This file was auto-generated by Fern from our API Definition.

package emails

import (
	context "context"
	fmt "fmt"
	mailmusgo "github.com/mailmus/mailmus-go"
	core "github.com/mailmus/mailmus-go/core"
	internal "github.com/mailmus/mailmus-go/internal"
	option "github.com/mailmus/mailmus-go/option"
	http "net/http"
)

type Client struct {
	baseURL string
	caller  *internal.Caller
	header  http.Header
}

func NewClient(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	return &Client{
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
		header: options.ToHeader(),
	}
}

func (c *Client) TransactionalEmailsSend(
	ctx context.Context,
	projectID string,
	request *mailmusgo.TransactionalEmailsSendRequest,
	opts ...option.RequestOption,
) (*mailmusgo.SendEmailResponseDto, error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		c.baseURL,
		"",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/projects/%v/emails",
		projectID,
	)
	headers := internal.MergeHeaders(
		c.header.Clone(),
		options.ToHeader(),
	)
	if request.IdempotencyKey != nil {
		headers.Add("Idempotency-Key", fmt.Sprintf("%v", *request.IdempotencyKey))
	}
	headers.Set("Content-Type", "application/json")

	var response *mailmusgo.SendEmailResponseDto
	if err := c.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
		},
	); err != nil {
		return nil, err
	}
	return response, nil
}

func (c *Client) TransactionalEmailsSendBatch(
	ctx context.Context,
	projectID string,
	request *mailmusgo.SendBatchEmailsDto,
	opts ...option.RequestOption,
) (*mailmusgo.BatchSendResponseDto, error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		c.baseURL,
		"",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/projects/%v/emails/batch",
		projectID,
	)
	headers := internal.MergeHeaders(
		c.header.Clone(),
		options.ToHeader(),
	)
	if request.IdempotencyKey != nil {
		headers.Add("Idempotency-Key", fmt.Sprintf("%v", *request.IdempotencyKey))
	}
	headers.Set("Content-Type", "application/json")

	var response *mailmusgo.BatchSendResponseDto
	if err := c.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
		},
	); err != nil {
		return nil, err
	}
	return response, nil
}

func (c *Client) TransactionalEmailsGetSendDetail(
	ctx context.Context,
	projectID string,
	sendID string,
	opts ...option.RequestOption,
) (*mailmusgo.SendDetailResponseDto, error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		c.baseURL,
		"",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/projects/%v/emails/logs/%v",
		projectID,
		sendID,
	)
	headers := internal.MergeHeaders(
		c.header.Clone(),
		options.ToHeader(),
	)

	var response *mailmusgo.SendDetailResponseDto
	if err := c.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
		},
	); err != nil {
		return nil, err
	}
	return response, nil
}

func (c *Client) TransactionalEmailsLogs(
	ctx context.Context,
	projectID string,
	request *mailmusgo.TransactionalEmailsLogsRequest,
	opts ...option.RequestOption,
) (*mailmusgo.SendLogListResponseDto, error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		c.baseURL,
		"",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/projects/%v/emails/logs",
		projectID,
	)
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		c.header.Clone(),
		options.ToHeader(),
	)

	var response *mailmusgo.SendLogListResponseDto
	if err := c.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
		},
	); err != nil {
		return nil, err
	}
	return response, nil
}
